# Modified from https://github.com/ColinPitrat/caprice32/blob/fed782e5a05180a90049360f60755f356d79634d/.travis.yml
language: cpp

# safelist
branches:
  only:
  - master

#To uncomment in case a core occurs:
#sudo: required
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
  packages:
    - git
    - ca-certificates
    - wget
    - make
    - patch
    - gcc
    - bzip2
    - unzip
    - g++
    - texinfo
    - bison
    - flex
    - libboost-dev
    - libncurses-dev
    - astyle
#To uncomment in case a core occurs:
#    - gdb
before_script:
    - export CXX=g++-4.8
# Build and test both in release and debug to ensure both works fine
script:
#To uncomment in case a core occurs:
# - ulimit -c unlimited
# - sudo sysctl kernel.core_pattern=core
 - pwd
 - ls -al
 - ./configure_cdtc_build_tree.sh
 - touch .build_dependencies_checked
 - make dsk -j2
 - make cdt -j2
 - make voc -j2
 - make au -j2
 - make -j2
#To uncomment in case a core occurs:
# - find ./ -name 'core*'
# - for i in $(find ./ -name 'core*' -print); do gdb ./test/test_runner $i -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
